# Generated by Django 3.2.13 on 2022-06-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=12)),
                ('sequence', models.CharField(max_length=300)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='taxanomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.CharField(max_length=12)),
                ('clade', models.CharField(max_length=2)),
                ('genus', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('protein_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxanomy', to='mainAPI.protein')),
            ],
        ),
        migrations.CreateModel(
            name='pfam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=10)),
                ('domain_descripton', models.CharField(max_length=200)),
                ('domains', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pfam', to='mainAPI.domains')),
            ],
        ),
        migrations.AddField(
            model_name='domains',
            name='protein_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='mainAPI.protein'),
        ),
    ]
