# Generated by Django 3.2.13 on 2022-06-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='hidden_domain_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
