# Generated by Django 3.2.13 on 2022-06-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0002_auto_20220625_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfam',
            name='domains',
        ),
        migrations.AddField(
            model_name='pfam',
            name='domains',
            field=models.ManyToManyField(to='mainAPI.domains'),
        ),
    ]
